In [1]:
#from google.colab import drive
#drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
import pandas as pd
df=pd.read_csv("Expresso_churn_dataset.csv")

In [2]:
df.head()

user_id  REGION         TENURE  MONTANT  \
0  00000bfd7d50f01092811bc0c8d7b0d6fe7c3596  FATICK   K > 24 month   4250.0   
1  00000cb4a5d760de88fecb38e2f71b7bec52e834     NaN  I 18-21 month      NaN   
2  00001654a9d9f96303d9969d0a4a851714a4bb57     NaN   K > 24 month   3600.0   
3  00001dd6fa45f7ba044bd5d84937be464ce78ac2   DAKAR   K > 24 month  13500.0   
4  000028d9e13a595abe061f9b58f3d76ab907850f   DAKAR   K > 24 month   1000.0   

   FREQUENCE_RECH  REVENUE  ARPU_SEGMENT  FREQUENCE  DATA_VOLUME  ON_NET  \
0            15.0   4251.0        1417.0       17.0          4.0   388.0   
1             NaN      NaN           NaN        NaN          NaN     NaN   
2             2.0   1020.0         340.0        2.0          NaN    90.0   
3            15.0  13502.0        4501.0       18.0      43804.0    41.0   
4             1.0    985.0         328.0        1.0          NaN    39.0   

   ORANGE  TIGO  ZONE1  ZONE2 MRG  REGULARITY                        TOP_PACK  \
0    46.0   1.0    1.0    2.0  NO          54  On net 200F=Unlimited _call24H   
1     NaN   NaN    NaN    NaN  NO           4                             NaN   
2    46.0   7.0    NaN    NaN  NO          17         On-net 1000F=10MilF;10d   
3   102.0   2.0    NaN    NaN  NO          62               Data:1000F=5GB,7d   
4    24.0   NaN    NaN    NaN  NO          11     Mixt 250F=Unlimited_call24H   

   FREQ_TOP_PACK  CHURN  
0            8.0      0  
1            NaN      1  
2            1.0      0  
3           11.0      0  
4            2.0      0

In [3]:
columns_to_drop = ['user_id','ZONE1','ZONE2','MRG']
df = df.drop(columns_to_drop, axis=1)

In [4]:
df

REGION         TENURE  MONTANT  FREQUENCE_RECH  REVENUE  \
0        FATICK   K > 24 month   4250.0            15.0   4251.0   
1           NaN  I 18-21 month      NaN             NaN      NaN   
2           NaN   K > 24 month   3600.0             2.0   1020.0   
3         DAKAR   K > 24 month  13500.0            15.0  13502.0   
4         DAKAR   K > 24 month   1000.0             1.0    985.0   
...         ...            ...      ...             ...      ...   
2154043     NaN   K > 24 month      NaN             NaN      NaN   
2154044   THIES   K > 24 month   6100.0            15.0   5800.0   
2154045     NaN   K > 24 month      NaN             NaN      NaN   
2154046   THIES   K > 24 month  10000.0            11.0   7120.0   
2154047     NaN   K > 24 month      NaN             NaN      NaN   

         ARPU_SEGMENT  FREQUENCE  DATA_VOLUME  ON_NET  ORANGE  TIGO  \
0              1417.0       17.0          4.0   388.0    46.0   1.0   
1                 NaN        NaN          NaN     NaN     NaN   NaN   
2               340.0        2.0          NaN    90.0    46.0   7.0   
3              4501.0       18.0      43804.0    41.0   102.0   2.0   
4               328.0        1.0          NaN    39.0    24.0   NaN   
...               ...        ...          ...     ...     ...   ...   
2154043           NaN        NaN          NaN     NaN     NaN   NaN   
2154044        1933.0       15.0        621.0    26.0    40.0  40.0   
2154045           NaN        NaN          NaN     NaN     NaN   NaN   
2154046        2373.0       13.0          NaN     0.0   140.0  13.0   
2154047           NaN        NaN          2.0     NaN     NaN   NaN   

         REGULARITY                        TOP_PACK  FREQ_TOP_PACK  CHURN  
0                54  On net 200F=Unlimited _call24H            8.0      0  
1                 4                             NaN            NaN      1  
2                17         On-net 1000F=10MilF;10d            1.0      0  
3                62               Data:1000F=5GB,7d           11.0      0  
4                11     Mixt 250F=Unlimited_call24H            2.0      0  
...             ...                             ...            ...    ...  
2154043           6                             NaN            NaN      0  
2154044          55           Data: 200 F=100MB,24H            9.0      0  
2154045           1                             NaN            NaN      1  
2154046          28           All-net 500F=2000F;5d           12.0      0  
2154047          62                             NaN            NaN      1  

[2154048 rows x 15 columns]

In [5]:
df['MONTANT'] = df['MONTANT'].fillna(df['MONTANT'].mean())
df['FREQUENCE_RECH'] = df['FREQUENCE_RECH'].fillna(df['FREQUENCE_RECH'].mean())
df['REVENUE'] = df['REVENUE'].fillna(df['REVENUE'].mode()[0])
df['ARPU_SEGMENT'] = df['ARPU_SEGMENT'].fillna(df['ARPU_SEGMENT'].median())
df['FREQUENCE'] = df['FREQUENCE'].fillna(df['FREQUENCE'].mean())
df['DATA_VOLUME'] = df['DATA_VOLUME'].fillna(df['DATA_VOLUME'].mode()[0])
df['ON_NET'] = df['ON_NET'].fillna(df['ON_NET'].mode()[0])
df['ORANGE'] = df['ORANGE'].fillna(df['ORANGE'].mode()[0])
df['TIGO'] = df['TIGO'].fillna(df['TIGO'].mode()[0])
df['FREQ_TOP_PACK'] = df['FREQ_TOP_PACK'].fillna(df['FREQ_TOP_PACK'].mean())


In [6]:
df.isnull().sum()

REGION            849299
TENURE                 0
MONTANT                0
FREQUENCE_RECH         0
REVENUE                0
ARPU_SEGMENT           0
FREQUENCE              0
DATA_VOLUME            0
ON_NET                 0
ORANGE                 0
TIGO                   0
REGULARITY             0
TOP_PACK          902594
FREQ_TOP_PACK          0
CHURN                  0
dtype: int64

In [7]:
df = df.dropna()
df.isnull().sum()

REGION            0
TENURE            0
MONTANT           0
FREQUENCE_RECH    0
REVENUE           0
ARPU_SEGMENT      0
FREQUENCE         0
DATA_VOLUME       0
ON_NET            0
ORANGE            0
TIGO              0
REGULARITY        0
TOP_PACK          0
FREQ_TOP_PACK     0
CHURN             0
dtype: int64

In [8]:
df.shape

(1000593, 15)

In [9]:
for i in df.columns:
  print(i,df[i].unique())

REGION ['FATICK' 'DAKAR' 'LOUGA' 'TAMBACOUNDA' 'KAOLACK' 'SAINT-LOUIS' 'THIES'
 'KAFFRINE' 'DIOURBEL' 'MATAM' 'KOLDA' 'ZIGUINCHOR' 'SEDHIOU' 'KEDOUGOU']
TENURE ['K > 24 month' 'H 15-18 month' 'I 18-21 month' 'F 9-12 month'
 'G 12-15 month' 'J 21-24 month' 'E 6-9 month' 'D 3-6 month']
MONTANT [ 4250. 13500.  1000. ... 18770.  8025.  2120.]
FREQUENCE_RECH [ 15.          1.         17.         16.          8.         27.
   7.         24.         46.         22.         12.          4.
  66.          2.         25.         63.         10.         11.
  19.         14.          6.         43.         37.         73.
  48.         29.         13.         40.          3.          5.
  31.          9.         20.         21.         18.         28.
  26.         41.         23.         47.         34.         61.
  45.         38.         70.         42.         50.         57.
  55.         44.         53.         65.         33.         72.
  35.         32.         59.         49.         

In [10]:
for i in df.columns:
  if df[i].dtype == 'object':
    print(i,df[i].unique())

REGION ['FATICK' 'DAKAR' 'LOUGA' 'TAMBACOUNDA' 'KAOLACK' 'SAINT-LOUIS' 'THIES'
 'KAFFRINE' 'DIOURBEL' 'MATAM' 'KOLDA' 'ZIGUINCHOR' 'SEDHIOU' 'KEDOUGOU']
TENURE ['K > 24 month' 'H 15-18 month' 'I 18-21 month' 'F 9-12 month'
 'G 12-15 month' 'J 21-24 month' 'E 6-9 month' 'D 3-6 month']
TOP_PACK ['On net 200F=Unlimited _call24H' 'Data:1000F=5GB,7d'
 'Mixt 250F=Unlimited_call24H' 'MIXT:500F= 2500F on net _2500F off net;2d'
 'All-net 500F=2000F;5d' 'On-net 500F_FNF;3d' 'Data: 100 F=40MB,24H'
 'MIXT: 200mnoff net _unl on net _5Go;30d' 'Jokko_Daily'
 'Data: 200 F=100MB,24H' 'Data:490F=1GB,7d' 'Twter_U2opia_Daily'
 'Data:1000F=2GB,30d' 'On-net 1000F=10MilF;10d' 'IVR Echat_Daily_50F'
 'Pilot_Youth4_490' 'On-net 500=4000,10d'
 'All-net 500F =2000F_AllNet_Unlimited' 'Twter_U2opia_Weekly'
 'Data:200F=Unlimited,24H' 'On-net 200F=60mn;1d' 'All-net 600F= 3000F ;5d'
 'All-net 1000F=(3000F On+3000F Off);5d' 'VAS(IVR_Radio_Daily)'
 'Data:3000F=10GB,30d' 'All-net 1000=5000;5d' 'Twter_U2opia_Monthly'
 'MI

In [11]:
pd.set_option('display.max_rows', None)
df['TOP_PACK'].value_counts()


TOP_PACK
All-net 500F=2000F;5d                                263214
On net 200F=Unlimited _call24H                       126299
Data:490F=1GB,7d                                      85890
Data: 100 F=40MB,24H                                  62576
Mixt 250F=Unlimited_call24H                           53890
MIXT:500F= 2500F on net _2500F off net;2d             53796
Data:1000F=2GB,30d                                    48374
All-net 500F =2000F_AllNet_Unlimited                  41717
Jokko_Daily                                           35084
Data: 200 F=100MB,24H                                 30108
On-net 500=4000,10d                                   21640
IVR Echat_Daily_50F                                   21384
MIXT: 200mnoff net _unl on net _5Go;30d               18082
On-net 1000F=10MilF;10d                               17090
On-net 500F_FNF;3d                                    16848
Data:200F=Unlimited,24H                               16575
VAS(IVR_Radio_Daily)           

In [12]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [13]:
country_map = shorten_categories(df.TOP_PACK.value_counts(), 200)
df['TOP_PACK'] = df['TOP_PACK'].map(country_map)
df.TOP_PACK.value_counts()

C:\Users\AUVIGHA TECH\AppData\Local\Temp\ipykernel_12736\3402331890.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TOP_PACK'] = df['TOP_PACK'].map(country_map)


TOP_PACK
All-net 500F=2000F;5d                          263214
On net 200F=Unlimited _call24H                 126299
Data:490F=1GB,7d                                85890
Data: 100 F=40MB,24H                            62576
Mixt 250F=Unlimited_call24H                     53890
MIXT:500F= 2500F on net _2500F off net;2d       53796
Data:1000F=2GB,30d                              48374
All-net 500F =2000F_AllNet_Unlimited            41717
Jokko_Daily                                     35084
Data: 200 F=100MB,24H                           30108
On-net 500=4000,10d                             21640
IVR Echat_Daily_50F                             21384
MIXT: 200mnoff net _unl on net _5Go;30d         18082
On-net 1000F=10MilF;10d                         17090
On-net 500F_FNF;3d                              16848
Data:200F=Unlimited,24H                         16575
VAS(IVR_Radio_Daily)                            10870
Data:1000F=5GB,7d                               10670
Twter_U2opia_Daily 

In [14]:
print(df.columns)

Index(['REGION', 'TENURE', 'MONTANT', 'FREQUENCE_RECH', 'REVENUE',
       'ARPU_SEGMENT', 'FREQUENCE', 'DATA_VOLUME', 'ON_NET', 'ORANGE', 'TIGO',
       'REGULARITY', 'TOP_PACK', 'FREQ_TOP_PACK', 'CHURN'],
      dtype='object')


In [15]:
for i in df.columns:
  print(i,df[i].dtype)


REGION object
TENURE object
MONTANT float64
FREQUENCE_RECH float64
REVENUE float64
ARPU_SEGMENT float64
FREQUENCE float64
DATA_VOLUME float64
ON_NET float64
ORANGE float64
TIGO float64
REGULARITY int64
TOP_PACK object
FREQ_TOP_PACK float64
CHURN int64


In [16]:
from sklearn.preprocessing import LabelEncoder
Region = LabelEncoder()
df['REGION'] = Region.fit_transform(df['REGION'])
df["REGION"].unique()
from sklearn.preprocessing import LabelEncoder
tenure = LabelEncoder()
df['TENURE'] = tenure.fit_transform(df['TENURE'])
df["TENURE"].unique()
from sklearn.preprocessing import LabelEncoder
top = LabelEncoder()
df['TOP_PACK'] = top.fit_transform(df['TOP_PACK'])
df["TOP_PACK"].unique()

C:\Users\AUVIGHA TECH\AppData\Local\Temp\ipykernel_12736\340230691.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['REGION'] = Region.fit_transform(df['REGION'])
C:\Users\AUVIGHA TECH\AppData\Local\Temp\ipykernel_12736\340230691.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TENURE'] = tenure.fit_transform(df['TENURE'])
C:\Users\AUVIGHA TECH\AppData\Local\Temp\ipykernel_12736\340230691.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usin

array([43, 14, 40, 37,  7, 48, 10, 34, 31, 11, 22, 54, 13, 44, 29, 51, 47,
        5, 56, 18, 45,  8,  2, 57, 19,  1, 55, 35, 27, 59, 17, 23, 39, 41,
       15, 49,  3, 20, 33, 28,  6, 36, 42,  0, 58, 53, 26, 12, 25, 21, 24,
       38, 46,  4,  9, 50, 32, 16, 30, 52])

In [17]:
df.to_csv('beforestandarization.csv')

In [18]:
df=pd.read_csv('beforestandarization.csv')

In [19]:
X = df.drop(['CHURN','Unnamed: 0'], axis=1)
y = df.CHURN

In [20]:
X.head()

REGION  TENURE  MONTANT  FREQUENCE_RECH  REVENUE  ARPU_SEGMENT  FREQUENCE  \
0       2       7   4250.0            15.0   4251.0        1417.0       17.0   
1       0       7  13500.0            15.0  13502.0        4501.0       18.0   
2       0       7   1000.0             1.0    985.0         328.0        1.0   
3       7       7   8500.0            17.0   9000.0        3000.0       18.0   
4       0       7   7000.0            16.0   7229.0        2410.0       22.0   

   DATA_VOLUME  ON_NET  ORANGE   TIGO  REGULARITY  TOP_PACK  FREQ_TOP_PACK  
0          4.0   388.0    46.0    1.0          54        43            8.0  
1      43804.0    41.0   102.0    2.0          62        14           11.0  
2          0.0    39.0    24.0    1.0          11        40            2.0  
3          0.0   252.0    70.0   91.0          62        37           18.0  
4       1601.0    77.0    29.0  100.0          55         7            8.0

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.1, random_state=1234)


In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Initialize the Decision Tree Classifier
clf = DecisionTreeClassifier(random_state=42)

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = clf.predict(X_test)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.9870977413551869


In [23]:
X_train[:2]

REGION  TENURE  MONTANT  FREQUENCE_RECH  REVENUE  ARPU_SEGMENT  \
705888      11       7  81464.0            19.0  10426.0        3475.0   
69624        2       7  24500.0            40.0  25500.0        8500.0   

        FREQUENCE  DATA_VOLUME  ON_NET  ORANGE  TIGO  REGULARITY  TOP_PACK  \
705888       40.0          0.0   841.0   830.0   7.0          62        37   
69624        42.0          0.0   157.0   427.0  97.0          62         7   

        FREQ_TOP_PACK  
705888            8.0  
69624            51.0

In [24]:
import numpy as np
data = [
    ['DAKAR', 'K > 24 month', 14950.0, 44.0, 15150.0, 5050.0, 52.0, 0.0, 141.0, 316.0, 151.0, 59.0, 'All-net 500F=2000F;5d', 23.0]
]

data_np = np.array(data)

print(data_np)

[['DAKAR' 'K > 24 month' '14950.0' '44.0' '15150.0' '5050.0' '52.0' '0.0'
  '141.0' '316.0' '151.0' '59.0' 'All-net 500F=2000F;5d' '23.0']]


In [25]:
data_np[:, 0] = Region.transform(data_np[:,0])
data_np[:, 1] = tenure.transform(data_np[:,1])
data_np[:, -2] = top.transform(data_np[:,-2])

data_np

array([['0', '7', '14950.0', '44.0', '15150.0', '5050.0', '52.0', '0.0',
        '141.0', '316.0', '151.0', '59.0', '7', '23.0']], dtype='<U32')

In [26]:
data_np=data_np.astype(float)
data_np

array([[0.000e+00, 7.000e+00, 1.495e+04, 4.400e+01, 1.515e+04, 5.050e+03,
        5.200e+01, 0.000e+00, 1.410e+02, 3.160e+02, 1.510e+02, 5.900e+01,
        7.000e+00, 2.300e+01]])

In [27]:
data_pred = clf.predict(data_np)
data_pred

c:\Users\AUVIGHA TECH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [28]:
import pickle


In [32]:
data = {"model": clf, "region": Region, "tenure": tenure,'top':top}
with open('churn.pkl', 'wb') as file:
    pickle.dump(data, file)

In [33]:
with open('churn.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
Region = data["region"]
top = data["top"]

In [31]:
y_pred = regressor_loaded.predict(data_np)
y_pred

c:\Users\AUVIGHA TECH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)